// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database_interfaces

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          string           `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Content     string           `json:"content"`
	Author      string           `json:"author"`
	Published   bool             `json:"published"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ModifiedAt  pgtype.Timestamp `json:"modified_at"`
}
