// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database_interfaces

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveComment = `-- name: ApproveComment :exec
UPDATE comments
SET approved = TRUE
WHERE id = $1
`

func (q *Queries) ApproveComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, approveComment, id)
	return err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
  id, title, description, content, author, published, created_at, modified_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, description, content, author, published, created_at, modified_at
`

type CreateArticleParams struct {
	ID          string           `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Content     string           `json:"content"`
	Author      string           `json:"author"`
	Published   bool             `json:"published"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ModifiedAt  pgtype.Timestamp `json:"modified_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Author,
		arg.Published,
		arg.CreatedAt,
		arg.ModifiedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Author,
		&i.Published,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (article_id, author_name, content)
VALUES ($1, $2, $3)
RETURNING id, article_id, author_name, content, approved, created_at, modified_at
`

type CreateCommentParams struct {
	ArticleID  string `json:"article_id"`
	AuthorName string `json:"author_name"`
	Content    string `json:"content"`
}

// --------------------------------------------------------------
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.ArticleID, arg.AuthorName, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.AuthorName,
		&i.Content,
		&i.Approved,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getApprovedCommentsByPost = `-- name: GetApprovedCommentsByPost :many
SELECT id, article_id, author_name, content, approved, created_at, modified_at
FROM comments
WHERE article_id = $1 AND approved = TRUE
ORDER BY created_at ASC
`

func (q *Queries) GetApprovedCommentsByPost(ctx context.Context, articleID string) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getApprovedCommentsByPost, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.AuthorName,
			&i.Content,
			&i.Approved,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticle = `-- name: GetArticle :one
SELECT id, title, description, content, author, published, created_at, modified_at FROM articles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetArticle(ctx context.Context, id string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Author,
		&i.Published,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getPendingComments = `-- name: GetPendingComments :many
SELECT id, article_id, author_name, content, approved, created_at, modified_at
FROM comments
WHERE approved = FALSE
ORDER BY created_at ASC
`

func (q *Queries) GetPendingComments(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getPendingComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.AuthorName,
			&i.Content,
			&i.Approved,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticles = `-- name: ListArticles :many
SELECT id, title, description, content, author, published, created_at, modified_at FROM articles
ORDER BY created_at
`

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Author,
			&i.Published,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles
SET title = $1, description = $2, content = $3, published = $4, modified_at = $5
WHERE id = $6
RETURNING id, title, description, content, author, published, created_at, modified_at
`

type UpdateArticleParams struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Content     string           `json:"content"`
	Published   bool             `json:"published"`
	ModifiedAt  pgtype.Timestamp `json:"modified_at"`
	ID          string           `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.Exec(ctx, updateArticle,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Published,
		arg.ModifiedAt,
		arg.ID,
	)
	return err
}
